# Generated by Django 2.0.8 on 2019-03-01 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='姓名')),
                ('id_number', models.CharField(default='', max_length=18, unique=True, verbose_name='身份证号码')),
                ('phone', models.CharField(default='', max_length=32, verbose_name='手机号码')),
            ],
            options={
                'verbose_name': '教练表',
                'verbose_name_plural': '教练表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CoachGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False)),
                ('cid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Coach', verbose_name='教练')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('单杠', '单杠'), ('双杠', '双杠'), ('吊环', '吊环'), ('自由体操', '自由体操'), ('鞍马', '鞍马'), ('蹦床', '蹦床'), ('高低杠', '高低杠'), ('平衡木', '平衡木')], max_length=32)),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=32, verbose_name='性别')),
                ('age_group', models.CharField(choices=[('7-8', '7-8'), ('9-10', '9-10'), ('11-12', '11-12')], default='7-8', max_length=32, verbose_name='年龄')),
            ],
            options={
                'verbose_name': '比赛项目表',
                'verbose_name_plural': '比赛项目表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1, unique=True, verbose_name='项目组号')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Competition', verbose_name='项目')),
            ],
            options={
                'verbose_name': '赛事分组表',
                'verbose_name_plural': '赛事分组表',
            },
        ),
        migrations.CreateModel(
            name='LeaderAndDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='姓名')),
                ('id_number', models.CharField(default='', max_length=18, unique=True, verbose_name='身份证号码')),
                ('phone', models.CharField(default='', max_length=32, verbose_name='手机号码')),
                ('place', models.CharField(choices=[('领队', '领队'), ('队医', '队医')], default='领队', max_length=32, verbose_name='职位')),
            ],
            options={
                'verbose_name': '领队-队医表',
                'verbose_name_plural': '领队-队医表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='账号')),
                ('password', models.CharField(default='', max_length=32, verbose_name='密码')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='姓名')),
                ('id_number', models.CharField(default='', max_length=18, unique=True, verbose_name='身份证号码')),
                ('phone', models.CharField(default='', max_length=32, verbose_name='手机号码')),
            ],
            options={
                'verbose_name': '裁判表',
                'verbose_name_plural': '裁判表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SportMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='姓名')),
                ('id_number', models.CharField(default='', max_length=18, unique=True, verbose_name='身份证号码')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=32, verbose_name='性别')),
                ('age_group', models.CharField(choices=[('7-8', '7-8'), ('9-10', '9-10'), ('11-12', '11-12')], default='7-8岁', max_length=32, verbose_name='组别')),
                ('grade', models.FloatField(blank=True, null=True, verbose_name='文化分数')),
            ],
            options={
                'verbose_name': '运动员表',
                'verbose_name_plural': '运动员表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SportManGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade1', models.FloatField(blank=True, null=True, verbose_name='得分1')),
                ('grade2', models.FloatField(blank=True, null=True, verbose_name='得分2')),
                ('grade3', models.FloatField(blank=True, null=True, verbose_name='得分3')),
                ('grade4', models.FloatField(blank=True, null=True, verbose_name='得分4')),
                ('grade5', models.FloatField(blank=True, null=True, verbose_name='得分5')),
                ('total_grade', models.FloatField(blank=True, null=True, verbose_name='最终得分')),
                ('gid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Group')),
                ('sid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.SportMan')),
            ],
            options={
                'verbose_name': '运动员比赛成绩',
                'verbose_name_plural': '运动员比赛成绩',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=32, unique=True, verbose_name='账号')),
                ('password', models.CharField(default='', max_length=32, verbose_name='密码')),
                ('name', models.CharField(default='', max_length=32, unique=True, verbose_name='代表队队名')),
                ('file', models.FileField(default='file/default', upload_to='file/')),
            ],
            options={
                'verbose_name': '代表队表',
                'verbose_name_plural': '代表队表',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='sportman',
            name='competition_group',
            field=models.ManyToManyField(through='sport.SportManGroup', to='sport.Group', verbose_name='报名分组'),
        ),
        migrations.AddField(
            model_name='sportman',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Team', verbose_name='所属代表队'),
        ),
        migrations.AddField(
            model_name='referee',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Team', verbose_name='所属代表队'),
        ),
        migrations.AddField(
            model_name='leaderanddoctor',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Team', verbose_name='所属代表队'),
        ),
        migrations.AlterUniqueTogether(
            name='competition',
            unique_together={('name', 'sex', 'age_group')},
        ),
        migrations.AddField(
            model_name='coachgroup',
            name='gid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Group', verbose_name='赛事分组'),
        ),
        migrations.AddField(
            model_name='coach',
            name='group',
            field=models.ManyToManyField(through='sport.CoachGroup', to='sport.Group', verbose_name='赛事分组'),
        ),
        migrations.AddField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Team', verbose_name='所属代表队'),
        ),
    ]
