# Generated by Django 2.0.8 on 2019-02-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分组名')),
            ],
            options={
                'verbose_name': '分组',
                'verbose_name_plural': '分组',
            },
        ),
        migrations.CreateModel(
            name='SportManCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade1', models.FloatField(verbose_name='得分1')),
                ('grade2', models.FloatField(verbose_name='得分2')),
                ('grade3', models.FloatField(verbose_name='得分3')),
                ('grade4', models.FloatField(verbose_name='得分4')),
                ('grade5', models.FloatField(verbose_name='得分5')),
            ],
            options={
                'verbose_name': '运动员比赛成绩',
                'verbose_name_plural': '运动员比赛成绩',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='代表队队名')),
            ],
            options={
                'verbose_name': '代表队表',
                'verbose_name_plural': '代表队表',
            },
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['id'], 'verbose_name': '比赛项目表', 'verbose_name_plural': '比赛项目表'},
        ),
        migrations.AlterModelOptions(
            name='sportman',
            options={'ordering': ['id'], 'verbose_name': '队员表', 'verbose_name_plural': '队员表'},
        ),
        migrations.AddField(
            model_name='competition',
            name='age_group',
            field=models.CharField(choices=[('7-8', '7-8'), ('9-10', '9-10'), ('11-12', '11-12')], default='7-8', max_length=32, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='competition',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=32, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='sportman',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='sportman',
            name='grade',
            field=models.FloatField(blank=True, null=True, verbose_name='文化分数'),
        ),
        migrations.AddField(
            model_name='sportman',
            name='id_number',
            field=models.CharField(default='', max_length=18, unique=True, verbose_name='身份证号码'),
        ),
        migrations.AddField(
            model_name='sportman',
            name='identity',
            field=models.CharField(choices=[('领队', '领队'), ('队医', '队医'), ('运动员', '运动员'), ('教练员', '教练员'), ('裁判员', '裁判员')], default='运动员', max_length=32, verbose_name='身份'),
        ),
        migrations.AddField(
            model_name='sportman',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='手机号码'),
        ),
        migrations.AddField(
            model_name='sportman',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=32, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(choices=[('单杠', '单杠'), ('双杠', '双杠'), ('吊环', '吊环'), ('自由体操', '自由体操'), ('鞍马', '鞍马'), ('蹦床', '蹦床')], max_length=32),
        ),
        migrations.AlterField(
            model_name='sportman',
            name='name',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterUniqueTogether(
            name='competition',
            unique_together={('name', 'sex', 'age_group')},
        ),
        migrations.AddField(
            model_name='sportmancompetition',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Competition'),
        ),
        migrations.AddField(
            model_name='sportmancompetition',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.SportMan'),
        ),
        migrations.AddField(
            model_name='sportman',
            name='competition',
            field=models.ManyToManyField(through='sport.SportManCompetition', to='sport.Competition'),
        ),
        migrations.AddField(
            model_name='sportman',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Group'),
        ),
        migrations.AddField(
            model_name='sportman',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Team'),
        ),
    ]
