# Generated by Django 2.0.8 on 2019-03-01 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefereeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False, verbose_name='小组总裁判')),
                ('gid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Group', verbose_name='赛事分组')),
                ('rid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Referee', verbose_name='裁判')),
            ],
        ),
        migrations.RemoveField(
            model_name='coachgroup',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='coachgroup',
            name='gid',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='group',
        ),
        migrations.DeleteModel(
            name='CoachGroup',
        ),
        migrations.AddField(
            model_name='referee',
            name='group',
            field=models.ManyToManyField(through='sport.RefereeGroup', to='sport.Group', verbose_name='赛事分组'),
        ),
    ]
