# Generated by Django 2.0.8 on 2019-02-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_auto_20190224_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportmancompetition',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Competition'),
        ),
        migrations.AlterField(
            model_name='sportmancompetition',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.SportMan'),
        ),
    ]
