# Generated by Django 2.0.8 on 2019-03-03 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_auto_20190301_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_team', to='sport.Team', verbose_name='所属代表队'),
        ),
        migrations.AlterField(
            model_name='group',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_competition', to='sport.Competition', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='leaderanddoctor',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_team', to='sport.Team', verbose_name='所属代表队'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='group',
            field=models.ManyToManyField(related_name='referee_group', through='sport.RefereeGroup', to='sport.Group', verbose_name='赛事分组'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee_team', to='sport.Team', verbose_name='所属代表队'),
        ),
        migrations.AlterField(
            model_name='sportman',
            name='competition_group',
            field=models.ManyToManyField(related_name='sport_man', through='sport.SportManGroup', to='sport.Group', verbose_name='报名分组'),
        ),
        migrations.AlterField(
            model_name='sportman',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport_man_team', to='sport.Team', verbose_name='所属代表队'),
        ),
    ]
