# Generated by Django 2.0.8 on 2019-03-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_auto_20190303_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='num',
            field=models.IntegerField(default=1, verbose_name='项目组号'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('num', 'competition')},
        ),
    ]
