# Generated by Django 2.0.8 on 2019-02-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_auto_20190224_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='file',
            field=models.FileField(default='file/default', upload_to='file/'),
        ),
    ]
