# Generated by Django 2.0.8 on 2019-03-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_auto_20190303_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.CharField(choices=[('初赛', '初赛'), ('决赛', '决赛')], default='初赛', max_length=32, verbose_name='初赛/决赛'),
        ),
        migrations.AlterField(
            model_name='group',
            name='num',
            field=models.IntegerField(default=0, verbose_name='项目组号'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('num', 'competition', 'level')},
        ),
    ]
