# Generated by Django 2.0.8 on 2019-02-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_team_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportmancompetition',
            name='grade1',
            field=models.FloatField(blank=True, null=True, verbose_name='得分1'),
        ),
        migrations.AlterField(
            model_name='sportmancompetition',
            name='grade2',
            field=models.FloatField(blank=True, null=True, verbose_name='得分2'),
        ),
        migrations.AlterField(
            model_name='sportmancompetition',
            name='grade3',
            field=models.FloatField(blank=True, null=True, verbose_name='得分3'),
        ),
        migrations.AlterField(
            model_name='sportmancompetition',
            name='grade4',
            field=models.FloatField(blank=True, null=True, verbose_name='得分4'),
        ),
        migrations.AlterField(
            model_name='sportmancompetition',
            name='grade5',
            field=models.FloatField(blank=True, null=True, verbose_name='得分5'),
        ),
    ]
