# Generated by Django 2.0.8 on 2019-03-12 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_auto_20190305_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('is_pass', models.BooleanField(default=True, verbose_name='是否通过')),
            ],
            options={
                'verbose_name': '打分表',
                'verbose_name_plural': '打分表',
            },
        ),
        migrations.AlterModelOptions(
            name='refereegroup',
            options={'verbose_name': '裁判分组表', 'verbose_name_plural': '裁判分组表'},
        ),
        migrations.RenameField(
            model_name='refereegroup',
            old_name='gid',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='refereegroup',
            old_name='rid',
            new_name='referee',
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('未开始', '未开始'), ('待打分', '待打分'), ('待审核', '待审核'), ('已确认', '已确认')], default='未开始', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(choices=[('单杠', '单杠'), ('双杠', '双杠'), ('吊环', '吊环'), ('自由体操', '自由体操'), ('鞍马', '鞍马'), ('蹦床', '蹦床'), ('跳马', '跳马'), ('高低杠', '高低杠'), ('平衡木', '平衡木')], max_length=32),
        ),
        migrations.AddField(
            model_name='score',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Group', verbose_name='赛事分组'),
        ),
        migrations.AddField(
            model_name='score',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Referee', verbose_name='裁判'),
        ),
        migrations.AddField(
            model_name='score',
            name='sport_man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.SportMan', verbose_name='运动员'),
        ),
    ]
