# Generated by Django 2.0.8 on 2019-02-26 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_auto_20190226_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '赛事分组', 'verbose_name_plural': '赛事分组'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.AddField(
            model_name='group',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Competition', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='group',
            name='num',
            field=models.IntegerField(default=1, unique=True, verbose_name='项目组号'),
        ),
    ]
