# Generated by Django 2.0.8 on 2019-03-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_auto_20190312_1438'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('referee', 'group', 'sport_man')},
        ),
    ]
