# Generated by Django 2.0.8 on 2019-02-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0007_auto_20190226_1702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refere',
            new_name='Referee',
        ),
    ]
