# Generated by Django 2.0.8 on 2019-04-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0009_auto_20190326_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportmangroup',
            name='d',
            field=models.FloatField(blank=True, null=True, verbose_name='奖励分'),
        ),
        migrations.AddField(
            model_name='sportmangroup',
            name='p',
            field=models.FloatField(blank=True, null=True, verbose_name='惩罚分'),
        ),
    ]
